install: devops
devops: arcplot.TS arcplot2.TS
	@echo up to date
arcplot.TS: arcplot.html arcplot.js
	cp arcplot.html arcplot.js  ../nodejs/data/
	date >arcplot.TS
arcplot2.TS: arcplot2.html arcplot2.js
	cp arcplot2.html arcplot2.js  ../nodejs/data/
	date >arcplot2.TS
